services:
  attacker:
    build: .
    hostname: attacker
    container_name: attacker
    tty: true
    stdin_open: true
    networks:
      nat_network1:
        ipv4_address: 172.16.1.5
    volumes:
      - .:/home/usr
# you need to run ./remote_shell manually when all other containers have started

  bot1:
    build: .
    hostname: bot1
    container_name: bot1
    tty: true
    stdin_open: true
    networks:
      nat_network1:
        ipv4_address: 172.16.1.5
    volumes:
      - .:/home/usr
    command: python3 bot.py -name bot1 -addr 172.16.1.5 -timeout 60

  bot2:
    build: .
    hostname: bot2
    container_name: bot2
    tty: true
    stdin_open: true
    networks:
      nat_network2:
        ipv4_address: 172.16.2.5
    volumes:
      - .:/home/usr
    command: python3 bot.py -name bot2 -addr 172.16.2.5 -timeout 60

networks:
  nat_network1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

  nat_network2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24