services:
  app1:
    build: .
    container_name: app1
    networks:
      - nat_network1
    command: ["python3", "/usr/app1.py", " tail -f /dev/null"]
    tty: true
    stdin_open: true

  app2:
    build: .
    container_name: app2
    networks:
      - nat_network2
    command: ["python3", "/usr/app2.py", "tail -f /dev/null"]
    tty: true
    stdin_open: true

  app3:
    build: .
    container_name: app3
    networks:
      - nat_network2
    command: ["python3", "/usr/app1.py", " tail -f /dev/null"]
    tty: true
    stdin_open: true

networks:
  nat_network1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

  nat_network2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24